#!/bin/bash
set -e

: "${PKG_CONFIG_PATH:=/usr/local/lib/pkgconfig}"
export PKG_CONFIG_PATH

CFLAGS=$(pkg-config --cflags libvalhalla)
LIBS=$(pkg-config --libs libvalhalla)
LIBDIR=$(pkg-config --variable=libdir libvalhalla)

clang++ -std=c++20 \
    -dynamiclib \
    -o libvalhalla_c.dylib \
    valhalla_c_api.cpp \
    $CFLAGS \
    -I/opt/homebrew/include \
    $LIBS \
    -L/opt/homebrew/lib \
    -Wl,-rpath,"$LIBDIR" \
    -Wl,-rpath,/usr/local/lib \
    -Wl,-rpath,/opt/homebrew/lib

echo "Built libvalhalla_c.dylib"
